spec:
  destination:
    project: system
    server: https://kubernetes.default.svc
certManager:
  enabled: true
elasticsearch:
  enabled: true
  values:
    antiAffinityTopologyKey: failure-domain.beta.kubernetes.io/zone
    esConfig:
      elasticsearch.yml: |
        http.max_content_length: 500mb
    rbac:
      create: true
elasticsearchCurator:
  enabled: true
  values:
    cronjob:
      schedule: 0 1 * * *
    configMaps:
      action_file_yml: |-
        ---
        actions:
          1:
            action: delete_indices
            description: "Clean up ES by deleting old indices"
            options:
              timeout_override:
              continue_if_exception: False
              disable_action: False
              ignore_empty_list: True
            filters:
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: days
              unit_count: 7
              field:
              stats_result:
              epoch:
              exclude: False
      config_yml: |-
        ---
        client:
          hosts:
            - elasticsearch-master
          port: 9200
fluentbit:
  enabled: false
fluentdElasticsearch:
  enabled: true
  values:
    elasticsearch:
      logstashPrefix: logs
      host: elasticsearch-master
metricsServer:
  enabled: true
nginxIngress:
  private:
    values:
      controller:
        extraArgs:
          enable-ssl-passthrough: ""
        ingressClass: nginx-internal
        publishService:
          enabled: true
        service:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
          omitClusterIP: true
        defaultBackend:
          service:
            omitClusterIP: true
  public:
    values:
      controller:
        extraArgs:
          enable-ssl-passthrough: ""
        ingressClass: nginx
        publishService:
          enabled: true
        service:
          omitClusterIP: true
        defaultBackend:
          service:
            omitClusterIP: true
sealedSecretsController:
  enabled: true
