elasticsearch:
  enabled: true
  values:
    antiAffinityTopologyKey: failure-domain.beta.kubernetes.io/zone
    esConfig:
      elasticsearch.yml: |
        http.max_content_length: 500mb
    rbac:
      create: true
fluentbit:
  enabled: false
fluentd:
  enabled: true
  values:
    elasticsearch:
      logstashPrefix: logs
      host: elasticsearch-master
metricsServer:
  enabled: true
spec:
  destination:
    project: system
    server: https://kubernetes.default.svc
