apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  description: System Applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: system
  source:
    path: applications/system/chart
    repoURL: https://github.com/bluesentry/argocd-demo.git
    helm: {}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-system
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: Namespace
metadata:
  name: log-system
spec:
  finalizers:
    - kubernetes
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: argocd-public-ingress
  namespace: argocd
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - &host argocd.bsisandbox.com
      secretName: *host
  rules:
  - host: *host
    http:
      paths:
      - path: /
        backend:
          serviceName: argocd-server
          servicePort: 8080