{{- if .Values.anchoreEngine.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: anchore-engine
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 2.16.0
    chart: anchore-engine
    {{- with .Values.anchoreEngine.values }}
    helm:
      values: |-
{{ toYaml . | indent 8 }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end -}}
