{{ if .Values.elasicsearch.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: log-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.5.1
    chart: elasticsearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  values: |-
    antiAffinityTopologyKey: failure-domain.beta.kubernetes.io/zone
    esConfig:
      elasticsearch.yml: |
        http.max_content_length: 500mb
    rbac:
      create: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: log-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  source:
    repoURL: 'https://helm.elastic.co'
    targetRevision: 7.5.1
    chart: kibana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{ end }}
