{{- if .Values.prometheusOperator.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 8.5.14
    chart: prometheus-operator
    {{- with .Values.prometheusOperator.values }}
    helm:
      values: |-
{{ toYaml . | indent 8 }}
    {{- end }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end -}}
