{{- if .Values.sealedSecretsController.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 1.5.0
    chart: sealed-secrets
    {{- with .Values.sealedSecretsController.values }}
    helm:
      values: |-
        {{ toYaml . | indent 8 }}
    {{- end -}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  {{- end -}}
