apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: kube-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 2.9.0
    chart: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
