{{ if .Values.metricsServer.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    repoURL: 'https://kubernetes-charts.storage.googleapis.com'
    targetRevision: 2.9.0
    chart: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  values: |-
    args:
      - --kubelet-preferred-address-types=InternalIP
{{ end }}
